#!/bin/sh

################################################################################
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

hdmimode=720p

for arg in $(cat /proc/cmdline); do
  case $arg in
    hdmimode=*)
      hdmimode="${arg#*=}"
      ;;
  esac
done

echo "$hdmimode" > /sys/class/display/mode

# set initial video state
echo 1 > /sys/class/video/disable_video

# setup framebuffer
echo 0 > /sys/class/graphics/fb0/blank
echo 1 > /sys/class/graphics/fb1/blank
echo 0 > /sys/class/graphics/fb0/free_scale

# Set framebuffer geometry to match the resolution
case "$hdmimode" in
  720*)
    fbset -fb /dev/fb0 -g 1280 720 1920 2160 32
    ;;
  1080*)
    fbset -fb /dev/fb0 -g 1920 1080 1920 2160 32
    ;;
esac

# Include deinterlacer into default VFM map
echo rm default > /sys/class/vfm/map
echo add default decoder ppmgr deinterlace amvideo > /sys/class/vfm/map
