#!/bin/bash

################################################################################
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

. config/options $1

if [ -f "$PKG_BUILD/configure.in" -o -f "$PKG_BUILD/configure.ac" ] ; then
  if [ ! -f $PKG_BUILD/.autoreconf-done ] ; then
    touch $PKG_BUILD/NEWS $PKG_BUILD/AUTHORS $PKG_BUILD/ChangeLog
    mkdir -p $PKG_BUILD/m4

    printf "%${BUILD_INDENT}c ${boldmagenta}AUTORECONF${endcolor}   $1\n" ' '
    export BUILD_INDENT=$((${BUILD_INDENT:-1}+4))

    do_autoreconf $PKG_BUILD
    touch $PKG_BUILD/.autoreconf-done
  fi
fi
