#!/bin/bash

################################################################################
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

. config/options $1

if [ -z "$1" ]; then
  echo "usage: $0 package_name[:<host|target|init|bootstrap>]"
  exit 1
fi

check_package $1
scripts/unpack $PACKAGE_NAME

mkdir -p $STAMPS/$PACKAGE_NAME
STAMP=$STAMPS/$PACKAGE_NAME/build_$TARGET

if [ -f $STAMP ] ; then
  . $STAMP
  check_deepmd5 || rm -f $STAMP
fi

if [ -f $STAMP ] ; then
  exit 0
fi

setup_toolchain $TARGET

unset -f pre_build_$TARGET
unset -f pre_configure_$TARGET
unset -f configure_$TARGET
unset -f pre_make_$TARGET
unset -f make_$TARGET
unset -f post_make_$TARGET
unset -f pre_makeinstall_$TARGET
unset -f makeinstall_$TARGET
unset -f post_makeinstall_$TARGET

CONFIGURE_OPTS_TARGET="--host=$TARGET_NAME \
                       --build=$HOST_NAME \
                       --prefix=/usr \
                       --bindir=/usr/bin \
                       --sbindir=/usr/sbin \
                       --sysconfdir=/etc \
                       --libexecdir=/usr/lib \
                       --localstatedir=/var \
                       --enable-silent-rules \
                       --disable-dependency-tracking"

CONFIGURE_OPTS_HOST="--host=$HOST_NAME \
                     --build=$HOST_NAME \
                     --prefix=$TOOLCHAIN \
                     --bindir=$TOOLCHAIN/bin \
                     --sbindir=$TOOLCHAIN/sbin \
                     --sysconfdir=$TOOLCHAIN/etc \
                     --libexecdir=$TOOLCHAIN/lib \
                     --localstatedir=$TOOLCHAIN/var \
                     --enable-silent-rules \
                     --disable-dependency-tracking"

CONFIGURE_OPTS_BOOTSTRAP="--host=$TARGET_NAME \
                          --build=$HOST_NAME \
                          --prefix=/usr \
                          --bindir=/usr/bin \
                          --sbindir=/usr/sbin \
                          --sysconfdir=/etc \
                          --libexecdir=/usr/lib \
                          --localstatedir=/var \
                          --enable-silent-rules \
                          --disable-dependency-tracking"

CONFIGURE_OPTS_INIT="--host=$TARGET_NAME \
                     --build=$HOST_NAME \
                     --prefix=/usr \
                     --bindir=/usr/bin \
                     --sbindir=/usr/sbin \
                     --sysconfdir=/etc \
                     --libexecdir=/usr/lib \
                     --localstatedir=/var \
                     --enable-silent-rules \
                     --disable-dependency-tracking"

. $PKG_DIR/package.mk
for p in `eval echo "\\$PKG_DEPENDS_$UPTARGET"`; do
  scripts/build $p
done

printf "%${BUILD_INDENT}c ${boldyellow}BUILD${endcolor}    $PACKAGE_NAME ${boldwhite}($TARGET)${endcolor}\n" ' '
export BUILD_INDENT=$((${BUILD_INDENT:-1}+4))

is_virtual=$(echo $PKG_DIR | awk -F "/" '{print $(NF-1)}')
if [ ! "$is_virtual" = "virtual" ]; then
  mkdir -p $PKG_BUILD
  cd $PKG_BUILD
  rm -rf $INSTALL

  if [ "$PKG_AUTORECONF" = yes ]; then
    do_autoreconf
  fi

  if [ "$(type -t pre_build_$TARGET)" = "function" ]; then
    pre_build_$TARGET
  fi

  if [ -f "$CONFIGURE_SCRIPT" -o -f "$CMAKE_SCRIPT" ]; then
    mkdir -p $PKG_BUILD_SUBDIR
  fi

  if [ "$(type -t pre_configure_$TARGET)" = "function" ]; then
    pre_configure_$TARGET
  fi

  if [ -n "$PKG_BUILD_SUBDIR" -a -d "$PKG_BUILD_SUBDIR" ] ; then
    cd $PKG_BUILD_SUBDIR
  fi

  if [ "$(type -t configure_$TARGET)" = "function" ]; then
    configure_$TARGET
  elif [ -f "$CONFIGURE_SCRIPT" ]; then
    eval $CONFIGURE_SCRIPT \$CONFIGURE_OPTS_$UPTARGET \$PKG_CONFIGURE_OPTS_$UPTARGET
  fi

  if [ "$(type -t pre_make_$TARGET)" = "function" ]; then
    pre_make_$TARGET
  fi
  if [ "$(type -t make_$TARGET)" = "function" ]; then
    make_$TARGET
  else
    eval make \$PKG_MAKE_OPTS_$UPTARGET
  fi
  if [ "$(type -t post_make_$TARGET)" = "function" ]; then
    post_make_$TARGET
  fi

  if [ "$(type -t pre_makeinstall_$TARGET)" = "function" ]; then
    pre_makeinstall_$TARGET
  fi
  if [ "$(type -t makeinstall_$TARGET)" = "function" ]; then
    makeinstall_$TARGET
  else
    case "$TARGET" in
      target|bootstrap)
        make install DESTDIR=$SYSROOT_PREFIX
        ;;&
      target|init)
        make install DESTDIR=$INSTALL
        ;;
      host)
        make install
        ;;
    esac
  fi
fi # ! virtual

if [ "$(type -t post_makeinstall_$TARGET)" = "function" ]; then
  post_makeinstall_$TARGET
fi

if [ "$TARGET" = "target" -o "$TARGET" = "init" ]; then
  if [ -d "$INSTALL" ] ; then
    rm -rf $INSTALL/{usr/,}include
    rm -rf $INSTALL/{usr/,}lib/cmake
    rm -rf $INSTALL/{usr/,}lib/pkgconfig
    rm -rf $INSTALL/{usr/,}man
    rm -rf $INSTALL/{usr/,}share/aclocal
    rm -rf $INSTALL/{usr/,}share/bash-completion
    rm -rf $INSTALL/{usr/,}share/doc
    rm -rf $INSTALL/{usr/,}share/gtk-doc
    rm -rf $INSTALL/{usr/,}share/info
    rm -rf $INSTALL/{usr/,}share/locale
    rm -rf $INSTALL/{usr/,}share/man
    rm -rf $INSTALL/{usr/,}share/pkgconfig
    rm -rf $INSTALL/{usr/,}share/zsh
    rm -rf $INSTALL/{usr/,}var
    find $INSTALL \( -name "*.orig" -o -name "*.la" -o -name "*.a" -o -name "*.o" -o -name "*.in" \) \
      -exec rm -f {} \; 2>/dev/null || :
    find $INSTALL -type d -exec rmdir -p {} \; 2>/dev/null || :

    if [ ! "$DEBUG" = yes ]; then
      debug_strip $INSTALL
    fi
    cleanup_rpath $INSTALL
  fi
fi
cd $ROOT

for i in `find $SYSROOT_PREFIX/usr/lib/ -name "*.la" 2>/dev/null`; do \
  sed -i "s:\(['= ]\)/usr:\\1$SYSROOT_PREFIX/usr:g" $i; \
done

save_stamp
