#!/bin/bash

################################################################################
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

. config/options $1

if [ -z "$1" ]; then
  echo "usage: $0 package_name"
  exit 1
fi

check_package $1
setup_toolchain target

pack_addon() {
  mkdir -p $ADDON_INSTALL

  if [ ! -f $ADDON_INSTALL/addon.xml ]; then
    cp config/addon/${PKG_ADDON_TYPE}/addon.xml $ADDON_INSTALL/addon.xml
    ADDONVER=$OS_VERSION.$PKG_ADDON_REV
  else
    ADDONVER=$(xmlstarlet sel -t -v "/addon/@version" $ADDON_INSTALL/addon.xml)
  fi

  cp -R $PKG_DIR/source/* $ADDON_INSTALL 2>/dev/null || :
  cp $PKG_DIR/icon/icon.png $ADDON_INSTALL 2>/dev/null || :
  cp $PKG_DIR/changelog.txt $ADDON_INSTALL 2>/dev/null || :

  if [ ! -f $ADDON_INSTALL/default.py -a \
      -f config/addon/$PKG_ADDON_TYPE/default.py ]; then
    cp config/addon/$PKG_ADDON_TYPE/default.py $ADDON_INSTALL/default.py
  fi

  PROVIDER_NAME="$DISTRONAME"
  if [ -n "$PKG_ADDON_MAINTAINER" ] ; then
    PROVIDER_NAME="$PKG_ADDON_MAINTAINER"
  fi
  ADDON_NAME="$PKG_NAME"
  if [ -n "$PKG_ADDON_NAME" ] ; then
    ADDON_NAME="$PKG_ADDON_NAME"
  fi
  sed -e "s|@PKG_ADDON_ID@|$PKG_ADDON_ID|g" \
      -e "s|@ADDON_NAME@|$ADDON_NAME|g" \
      -e "s|@OS_VERSION@|$OS_VERSION.$PKG_ADDON_REV|g" \
      -e "s|@PKG_SHORTDESC@|$PKG_SHORTDESC|g" \
      -e "s|@OS_VERSION@|$OS_VERSION|g" \
      -e "s|@PKG_ADDON_DESC@|$PKG_ADDON_DESC|g" \
      -e "s|@PKG_ADDON_DISCLAIMER@|$PKG_ADDON_DISCLAIMER|g" \
      -e "s|@PROVIDER_NAME@|$PROVIDER_NAME|g" \
      -i $ADDON_INSTALL/addon.xml

  cd $ADDON_BUILD
  cleanup_rpath $PKG_ADDON_ID
  if [ ! "$DEBUG" = yes ]; then
    debug_strip $PKG_ADDON_ID
  fi

  zip -rq $PKG_ADDON_ID-$ADDONVER.zip $PKG_ADDON_ID
  cd - &>/dev/null

  ADDON_INSTALL_DIR="target/addons/$OS_VERSION/$PROJECT/$TARGET_ARCH/$PKG_ADDON_ID"
  if [ -f $ADDON_INSTALL_DIR/$PKG_ADDON_ID-$ADDONVER.zip ] ; then
    echo "*** WARNING: $ADDON_INSTALL_DIR/$PKG_ADDON_ID-$ADDONVER.zip exists. not overwriting it"
    echo "*** WARNING: your addon is at $ADDON_INSTALL-$ADDONVER.zip"
    return 0
  fi

  mkdir -p $ADDON_INSTALL_DIR
  cp $ADDON_INSTALL-$ADDONVER.zip $ADDON_INSTALL_DIR
  cp $ADDON_INSTALL/changelog.txt $ADDON_INSTALL_DIR/changelog-$ADDONVER.txt 2>/dev/null || :
  cp $ADDON_INSTALL/icon.png $ADDON_INSTALL_DIR/icon.png 2>/dev/null || :
  echo "*** DONE: $ADDON_INSTALL_DIR/$PKG_ADDON_ID-$ADDONVER.zip"
}

if [ "$PKG_IS_ADDON" = "yes" ] ; then
  PKG_ADDON_ID="$PKG_NAME"
  if [ -n "$PKG_ADDON_SECTION" ] ; then
    PKG_ADDON_ID="`echo $PKG_ADDON_SECTION | sed 's,/,.,g'`.$PKG_NAME"
  fi
  ADDON_BUILD="$BUILD/addons/$PKG_NAME"
  ADDON_INSTALL="$ADDON_BUILD/$PKG_ADDON_ID"

  rm -rf $ADDON_BUILD $ADDON_INSTALL

  if [ "$(type -t addon)" = "function" ]; then
    scripts/build $@
    printf  "%${BUILD_INDENT}c CREATE ADDON  ($PROJECT/$TARGET_ARCH) $1\n" ' '
    export BUILD_INDENT=$((${BUILD_INDENT:-1}+4))
    addon
    pack_addon
  else
    echo "*** ERROR: $PKG_NAME does not have addon() defined"
    exit 1
  fi
fi
