#!/bin/bash

################################################################################
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

. config/options $1

if [ -z "$1" ]; then
  echo "usage: $0 package_name|-a"
  exit 1
fi

if [ "$1" == "-a" ]; then
  for i in `find packages/ -type f -name package.mk`; do
    PKG_NAME=""
    . $i
    $SCRIPTS/get $PKG_NAME
  done
  exit 0
fi

if [ -n "$PKG_URL" ] ; then
  SOURCE_NAME="`basename $PKG_URL`"
elif [ -n "$PKG_FETCH" ] ; then
  SOURCE_NAME="$PKG_NAME-$PKG_VERSION.tar.gz"
fi

if [ -z "$SOURCE_NAME" ] ; then
  exit 0
fi

STAMP="$SOURCES/$1/$SOURCE_NAME.url"
if [ -f "$STAMP" ]; then
  exit
fi

printf "%${BUILD_INDENT}c ${boldcyan}GET${endcolor}      $1\n" ' '
export BUILD_INDENT=$((${BUILD_INDENT:-1}+$BUILD_INDENT_SIZE))

mkdir -p $SOURCES/$1

if [ -n "$PKG_FETCH" ] ; then
  VCS=$(echo $PKG_FETCH | grep "+" | awk -F '+' '{print $1}')
  if [ -n "$VCS" ] ; then
    GET_REPO=$(echo $PKG_FETCH | awk -F '+' '{print $2}')
    if [ -n $GET_REPO ] ; then
      $SCRIPTS/mkpkg $PKG_NAME $PKG_VERSION
    fi
  fi
elif [ -n "$PKG_URL" ] ; then
  PACKAGE_MIRROR="$DISTRO_MIRROR/$PKG_NAME/$SOURCE_NAME"
  WGET_CMD="wget --timeout=30 --tries=2 --no-check-certificate -c -nv --show-progress -P $SOURCES/$1"
  NBWGET="1"
  until [ -f "$STAMP" ] || $WGET_CMD $PKG_URL || $WGET_CMD $PACKAGE_MIRROR ; do
    NBWGET=$(($NBWGET+1))
    if [ "$NBWGET" -gt "2" ]; then
      echo "*** Cant't get $1 sources : $PKG_URL. Try later ***"
      exit 1
    fi
  done
fi
echo $SOURCE_NAME > $STAMP
