#!/bin/bash

################################################################################
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

. config/options $1

check_root
show_config

scripts/checkdeps
scripts/build toolchain

BUILD_DATE=`date +%Y%m%d%H%M%S`
GIT_ABBREV=$(git log -1 --pretty=format:%h)
DISTRO_VERSION=$OS_VERSION.$BUILD_DATE.$GIT_ABBREV
IMAGE_NAME="$DISTRONAME.$PROJECT.$DISTRO_VERSION"

# clean old install dirs
rm -rf $INSTALL_IMAGE $STAMPS_INSTALL
mkdir -p $INSTALL_IMAGE

# create baselayout
mkdir -p $INSTALL_IMAGE/bin
mkdir -p $INSTALL_IMAGE/etc
mkdir -p $INSTALL_IMAGE/lib
mkdir -p $INSTALL_IMAGE/sbin
mkdir -p $INSTALL_IMAGE/dev
mkdir -p $INSTALL_IMAGE/proc
mkdir -p $INSTALL_IMAGE/run
mkdir -p $INSTALL_IMAGE/sys
mkdir -p $INSTALL_IMAGE/tmp
mkdir -p $INSTALL_IMAGE/usr
mkdir -p $INSTALL_IMAGE/var
mkdir -p $INSTALL_IMAGE/flash
mkdir -p $INSTALL_IMAGE/storage
ln -sf /var/media $INSTALL_IMAGE/media

# Basissystem...
scripts/install base
scripts/install mediacenter

# create /etc/os-release
echo -e "NAME=\"$DISTRONAME\"" > $INSTALL_IMAGE/etc/os-release
echo -e "VERSION=\"$DISTRO_VERSION\"" >> $INSTALL_IMAGE/etc/os-release
echo -e "ID=\"openelec\"" >> $INSTALL_IMAGE/etc/os-release
echo -e "VERSION_ID=\"$OS_VERSION\"" >> $INSTALL_IMAGE/etc/os-release
echo -e "PRETTY_NAME=\"$DISTRONAME - $DISTRO_VERSION\"" >> $INSTALL_IMAGE/etc/os-release

# create /etc/issue
echo "$DISTRONAME - $DISTRO_VERSION" >> $INSTALL_IMAGE/etc/issue
ln -sf /etc/issue $INSTALL_IMAGE/etc/motd

# copy project related files to filesystem
if [ -d "$PROJECT_DIR/$PROJECT/filesystem" ]; then
  cp -PR $PROJECT_DIR/$PROJECT/filesystem/* $INSTALL_IMAGE
  # install project specific systemd services
  for service in $PROJECT_DIR/$PROJECT/filesystem/usr/lib/systemd/system/*.service ; do
    if [ -f "$service" ] ; then
      enable_service $(basename $service)
    fi
  done
fi

# run depmod
MODVER=$(basename $(ls -d $INSTALL_IMAGE/lib/modules/*))
find $INSTALL_IMAGE/lib/modules/$MODVER/ -name *.ko | \
  sed -e "s,$INSTALL_IMAGE/lib/modules/$MODVER/,," > $INSTALL_IMAGE/lib/modules/$MODVER/modules.order
$TOOLCHAIN/bin/depmod -b $INSTALL_IMAGE $MODVER > /dev/null

# make target dir
mkdir -p $TARGET_IMG

cp -PR $BUILD/linux-*/arch/$TARGET_KERNEL_ARCH/boot/$KERNEL_TARGET $TARGET_IMG/$IMAGE_NAME.kernel
mksquashfs $INSTALL_IMAGE $TARGET_IMG/$IMAGE_NAME.system -all-root -no-xattrs -noappend -comp gzip

# release
RELEASE_DIR="target/$IMAGE_NAME"
rm -rf $RELEASE_DIR
mkdir -p $RELEASE_DIR

cp $TARGET_IMG/$IMAGE_NAME.system $RELEASE_DIR/root.sqfs
cp $TARGET_IMG/$IMAGE_NAME.kernel $RELEASE_DIR/kernel.img
tar cf $TARGET_IMG/$IMAGE_NAME.tar -C $RELEASE_DIR .

# clean up
rm -rf $RELEASE_DIR
rm -f $TARGET_IMG/$IMAGE_NAME.system
rm -f $TARGET_IMG/$IMAGE_NAME.kernel
