#!/bin/bash

################################################################################
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

. config/options $1

if [ -z "$1" ]; then
  echo "usage: $0 package_name [-b]"
  exit 1
fi

check_package $1

PACKAGE_NAME=$(echo $1 | awk -F : '{print $1}')
TARGET=$(echo $1 | awk -F : '{print $2}')
if [ -z "$TARGET" ]; then
  TARGET="target"
fi

case "$2" in
  -b)
    STAMP=$STAMPS/$PACKAGE_NAME/build_$TARGET
    STEP=BUILD
    $0 $1 -u
    ;;
  -u|"")
    STAMP=$PKG_BUILD/.openelec-unpack
    STEP=UNPACK
    ;;
esac

if [ -f $STAMP ] ; then
  rm -f $STAMP

  printf "%${BUILD_INDENT}c ${boldcyan}SKIP_$STEP${endcolor}   $1\n" ' '
  export BUILD_INDENT=$((${BUILD_INDENT:-1}+4))

  save_stamp
fi
